Refactor ulib
arceos-org/arceos pull request #105
Opened 2023-07-23 16:00 UTC by equation314

- move cbindings out of `libax` as a new crate `axlibc`
- rename `libax` to `axstd`
- make APIs in `axstd` more similar to rust std
- now apps can be built with both std and ArceOS without modification

2023-07-24 01:36 UTC, chyyuu requested changes
suggest :   scope of  arceos_api > scope of arceos_api_posix , so     "arceos_api"  --> "arceos_std_api" ;  musllic is used for linux, not only posix,  "arceos_api_posix" --> "arceos_linux_api"

2023-07-24 05:13 UTC, equation314 commented
I think the linux API is at the syscall level, and the POSIX API is at the library function level. The ArceOS API layer is not only syscalls, but also includes high-level library functions, and it is more appropriately called `arceos_api_posix`.

Called `arceos_api` instead of `arceos_std_api` because the name is too long.

2023-07-24 08:45 UTC, equation314 commented
`arceos_api` -> `arceos_rust_api` ?

2023-07-25 02:18 UTC, chyyuu approved these changes

2023-07-25 02:19 UTC, merged