Libc: More libc functions for Redis(Part 3)
arceos-org/arceos pull request #108
Opened 2023-07-26 04:46 UTC by coolyjg

Most of this pr are function declarations and "unimplemented" definitions, EXCEPT: 
- `rename` implementation.
- `pow` and `log` implementated by C.
- `sysfs` and `procfs` implemented by `ramfs`.
- `mktime` and `strftime` implemented by Rust, following relibc.

2023-07-26 11:59 UTC, equation314 commented
Removed `ulib/libax`, `ulib/c_libax`

2023-07-26 15:06 UTC, equation314 requested changes

2023-07-26 15:06 UTC, equation314 commented on ulib/axlibc/c/file.c
`file.c` -> `flock.c`

2023-07-26 15:06 UTC, equation314 commented on ulib/axlibc/c/netdb.c
> +const char *gai_strerror(int ecode)
Move to `network.c` near `getaddrinfo`/`freeaddrinfo`

2023-07-26 15:06 UTC, equation314 commented on ulib/axlibc/c/network.c
> +static __inline uint64_t __bswap_64(uint64_t __x)
Not used?

2023-07-26 15:06 UTC, equation314 commented on ulib/axlibc/src/file.rs
> +        match fs::rename(old_path, new_path) {
Returns `fs::rename(old_path, new_path)` directly

2023-07-26 15:06 UTC, equation314 commented on ulib/axlibc/src/mktime.rs
> +pub unsafe extern "C" fn ax_mktime(t: *mut ctypes::tm) -> ctypes::time_t {
Call `ax_mktime` in C function `mktime`

2023-07-26 15:06 UTC, equation314 commented on ulib/axlibc/c/pwd.c
> +static int getpw_r(const char *name, uid_t uid, struct passwd *pw, char *buf, size_t size,
Password-related functions are not planning to support in ArceOS, leave them unimplemented.

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/src/api/mod.rs
> +/// Renames a file
Add more detailed comments like the rust std library, and add comments about the limitation.

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/src/fops.rs
> +    pub fn rename(&self, old: &str, new: &str) -> AxResult {
Add comments about the limitation.

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/src/fs/fatfs.rs
> +
Add comments about the limitation.

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/Cargo.toml
> +procfs = []
More these two lines after `ramfs`, and add dependencies to `dep:axfs_ramfs`.

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/src/root.rs
> +#[cfg(all(feature = "ramfs", feature = "procfs"))]
Remove `feature = "ramfs"`

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/src/root.rs
> +fn mount_procfs() -> fs::ramfs::RamFileSystem {
Two many `unwrap`s, use the `?` expression.

2023-07-26 15:06 UTC, equation314 commented on modules/axfs/src/root.rs
> +    // Mount another ramfs as procfs
Move code pieces about `devfs` and `ramfs` as two separated functions.

2023-07-26 16:30 UTC, coolyjg commented on ulib/axlibc/src/file.rs
> +        match fs::rename(old_path, new_path) {
The error type does not match

2023-07-27 05:47 UTC, equation314 commented on ulib/axlibc/src/file.rs
> +        fs::rename(old_path, new_path).map_or_else(|e| Err(LinuxError::from(e)), |_| Ok(0))
```rust
axstd::fs::rename(old_path, new_path)?;
Ok(0)
```

2023-07-27 05:47 UTC, equation314 commented on ulib/axlibc/c/network.c
> +#define bswap_32(x) __bswap_32(x)
These two definitions are not used

2023-07-27 05:47 UTC, equation314 commented on ulib/axlibc/c/network.c
> +static const char msgs_lc[] = "Invalid flags\0"
`gai_msgs`

2023-07-27 05:47 UTC, equation314 commented on ulib/axlibc/c/network.c
> +    return LCTRANS_CUR(s);
`return s;` is okay

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +    #[cfg(all(feature = "ramfs", feature = "procfs"))]
`#[cfg(feature = "procfs")]`

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +    root_dir // should not fail
`#[cfg(feature = "sysfs")]`

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +fn mount_devfs() -> fs::devfs::DeviceFileSystem {
Returns `Arc<...>` for all `mount_*` functions.

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +fn mount_devfs() -> fs::devfs::DeviceFileSystem {
Move these 4 `mount_*fs()` functions into a new file `mounts.rs`, and rename to `mounts::devfs()`, `mounts::ramfs()`, ...

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +    file_somaxconn.write_at(0, b"4096")?;
`\n`

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +    file_over.write_at(0, b"0")?;
`\n`

2023-07-27 05:47 UTC, equation314 commented on modules/axfs/src/root.rs
> +                ax_err!(NotFound)
```rust
ax_err!(PermissionDenied) // cannot rename mount points
```

2023-07-27 05:55 UTC, equation314 commented on ulib/axlibc/c/pthread.c
>      ax_pthread_mutex_init(m, a);
`pthread_mutex_*` should return the values return by `ax_pthread_mutex_*`.

2023-07-27 06:50 UTC, equation314 approved these changes

2023-07-27 07:08 UTC, merged