Add udp and dns support 添加udp和dns支持
arceos-org/arceos pull request #24
Opened 2023-04-14 18:30 UTC by reflyable

接入smoltcp udp和dns socket, 实现对应udp栈和dns相关的Trait，增加相应rust app

2023-04-21 15:44 UTC, equation314 requested changes

2023-04-21 15:44 UTC, equation314 commented on Cargo.toml
> +    # "apps/net/httpclient",
Uncomment it, and remove line 13

2023-04-21 15:44 UTC, equation314 commented on Cargo.toml
> +
Remove the Tab

2023-04-21 15:44 UTC, equation314 commented on apps/net/httpclient/Cargo.toml
> +dns = []
Add blank line at the end of file

2023-04-21 15:44 UTC, equation314 commented on apps/net/httpclient/src/main.rs
> +const DEST_HOST: &str = "www.example.com";
Why use "www.example.com" instead of "ident.me"?

2023-04-21 15:44 UTC, equation314 commented on apps/net/httpclient/Cargo.toml
> +libax = { path = "../../../ulib/libax", features = ["paging", "multitask", "net"] }
Why use  "multitask"?

2023-04-21 15:44 UTC, equation314 commented on apps/net/httpclient/Cargo.toml
> -authors = ["Yuekai Jia <equation618@gmail.com>"]
Add your email here

2023-04-21 15:44 UTC, equation314 commented on apps/net/udpserver/src/main.rs
> +#[no_mangle]
Add blank line

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/Cargo.toml
> +  "socket-raw", "socket-icmp", "socket-udp", "socket-tcp","socket-dns"
Add a space before "socket-dns"

2023-04-21 15:44 UTC, equation314 commented on apps/net/udpserver/src/main.rs
> +    println!("listen on: http://{}/", socket.local_addr().unwrap());
Do not use `http://`

2023-04-21 15:44 UTC, equation314 commented on apps/net/udpserver/src/main.rs
> +fn accept_loop() -> io::Result {
UDP socket does not use `accept()`, rename the function, e.g., `receive_loop()`

2023-04-21 15:44 UTC, equation314 commented on apps/net/httpclient/src/main.rs
> +    {
I think the original version is fine, this code leads to the example is not simple enough.

2023-04-21 15:44 UTC, equation314 commented on apps/net/udpserver/Cargo.toml
> +authors = ["Dashuai Wu"]
Add your email

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/udp.rs
> +/// A TCP socket.
Fix this, and add a blank line before the comment and `use ...`

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/udp.rs
> +    /// Returns the socket address that this socket was created from.
Add blank lines between two functions.

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/udp.rs
> +    ///Receives a message on the socket.
Add a space after `///`

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/udp.rs
> +    ///Sends data on the socket to the given address.
Add a space after `///`

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/socket_addr.rs
> +/// A trait for objects which can be converted or resolved to one or more SocketAddr values.
use ``[`SocketAddr`]``, add a blank line before the comment.

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/socket_addr.rs
> +    ///Converts this object to an iterator of resolved SocketAddrs.
use [`SocketAddr`], add a blank line before the comment.

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/socket_addr.rs
> +        // if let Ok(addr) = host.parse::<Ipv6Addr>() {
Remove the unused code

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/udp.rs
> +    socket: _UdpSocket,
Use `axnet::UdpSocket` here,

2023-04-21 15:44 UTC, equation314 commented on ulib/libax/src/net/socket_addr.rs
> +fn resolve_socket_addr(name: &str) -> io::Result<alloc::vec::Vec<IpAddr>> {
Move this function into `axnet`

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/lib.rs
> +pub use self::net_impl::DnsSocket;
Do not export `DnsSocket`

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/lib.rs
> +    DnsQueryType, IpAddress as IpAddr, IpEndpoint as SocketAddr, Ipv4Address as Ipv4Addr,
Do not export `DnsQueryType`

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/dns.rs
> +/// [`update_servers`]: UDPSocket::update_servers
Remove the tow comments

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/mod.rs
> +pub use self::dns::DnsSocket;
Do not export `DnsSocket`

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +/// [`bind`]: UDPSocket::bind
Remove these comments

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +        debug!("{:?}", addr);
Add more detail debug info ,or just remove it

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +        debug!("{:?}", addr);
Same as above

2023-04-21 15:44 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/mod.rs
> +    } else if ipv4_packet.next_header() == IpProtocol::Udp {
Remove this `else if`

2023-04-21 16:10 UTC, reflyable commented on apps/net/httpclient/src/main.rs
> +const DEST_HOST: &str = "www.example.com";
ident.me的reply太短，原有的实现方式在获得的包长大于1500(MTU)时会截断，在原来的httpclient用www.example.com可以复现这个问题。"www.example.com"也能更好地体现是一个http response

2023-04-21 17:23 UTC, equation314 requested changes

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/dns.rs
> +/// [`query`]: UDPSocket::query
Fix the comment

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/mod.rs
> +    pub fn new_udp_socket() -> socket::udp::Socket<'a> {
Add a new line before

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +pub struct UdpSocket {
Fix the unclear comments

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +    /// Transmits data in the given buffer to the given address.
Add a new line before

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +    pub fn recvfrom(&self, buf: &mut [u8]) -> AxResult<(usize, SocketAddr)> {
Add a new line before

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +    pub fn shutdown(&self) -> AxResult {
Add a new line before

2023-04-21 17:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +    /// Receives data from the socket, stores it in the given buffer, without removing it from the queue.
Add a new line before

2023-04-21 17:23 UTC, equation314 commented on ulib/libax/src/net/socket_addr.rs
> +    /// Converts this object to an iterator of resolved [`SocketAddr`]s.
Add a new line before

2023-04-21 17:23 UTC, equation314 commented on apps/net/httpclient/src/main.rs
> +        "GET / HTTP/1.1\r\nHost: ".to_string() + DEST_HOST + "\r\nAccept: */*\r\n\r\n";
Use the original `REQUEST` constant.

2023-04-21 17:23 UTC, equation314 commented on apps/net/httpclient/expect_info.out
> +Content-Length: 14
Remove `14`, or other IP may cause test failure.

2023-04-21 17:23 UTC, equation314 commented on apps/net/httpclient/expect_info_dns.out
> +Content-Length: 14
Remove `14`

2023-04-21 17:23 UTC, equation314 commented on scripts/test/app_test.sh
Do not change this file

2023-04-22 07:20 UTC, equation314 requested changes

2023-04-22 07:20 UTC, equation314 commented on apps/net/udpserver/src/main.rs
> +fn recive_loop() -> io::Result {
typo

2023-04-22 07:20 UTC, equation314 commented on apps/net/udpserver/src/main.rs
> +    println!("listen on: {}/", socket.local_addr().unwrap());
Remove the `/`

2023-04-22 07:20 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/dns.rs
> +/// A Dns socket.
Use uppercase: `DNS`

2023-04-22 07:20 UTC, equation314 commented on modules/axnet/src/lib.rs
Update crate-level documents: line 3, line 9-11

2023-04-22 08:20 UTC, equation314 approved these changes

2023-04-22 08:28 UTC, merged