net for c_libax
arceos-org/arceos pull request #42
Opened 2023-05-12 07:07 UTC by reflyable

实现c_libax中网络接口
- socket
- shutdown
- bind
- connect
- listen
- accept
- send
- recv
- sendto
- recvfrom
- htonl
- htons
- ntohl
- ntohs
- inet_pton
- inet_ntop
- getaddrinfo(功能不完全)
- freeaddrinfo

2023-05-13 07:31 UTC, equation314 requested changes

2023-05-13 07:31 UTC, equation314 commented on .github/workflows/build.yml
> +      run: PATH=$PATH:$PWD/musl/bin make ARCH=${{ matrix.arch }} A=apps/c/httpclient
Add other c apps for CI build.

2023-05-13 07:31 UTC, equation314 commented on apps/c/httpclient/axbuild.mk
> +app-objs := httpclient.o
Add a newline at EOF

2023-05-13 07:31 UTC, equation314 commented on apps/c/sqlite3/features.txt
> +fs
Why this file is changed?

2023-05-13 07:31 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +fn get_ephemeral_port() -> AxResult<u16> {
Same as `tcp::get_ephemeral_port`, is it possible to keep only one?

2023-05-13 07:31 UTC, equation314 commented on apps/c/httpclient/httpclient.c
> +const char *buf = "\
Rename to `request`

2023-05-13 07:31 UTC, equation314 commented on apps/c/httpclient/httpclient.c
> +    send(sock, buf, 47, 0);
Use `strlen` instead of hardcode.

2023-05-13 07:31 UTC, equation314 commented on apps/c/httpclient/httpclient.c
> +}
Add a new line at EOF.

2023-05-13 07:31 UTC, equation314 commented on apps/c/httpserver/httpserver.c
> +Content-Length: 340\r\n\
Avoid hardcoding

2023-05-13 07:31 UTC, equation314 commented on apps/c/udpserver/udpserver.c
> +int main()
Add a newline before.

2023-05-13 07:31 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +    /// Transmits data in the given buffer to the connected address.
Wrong comments.

2023-05-13 07:31 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
Why use this check?

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +struct addrinfo {
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +#define AI_PASSIVE     0x01
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/netinet/in.h
> +uint32_t htonl(uint32_t);
These 4 defines should be put in arpa/inet.h

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/netinet/in.h
> +#endif
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/netinet/in.h
> +struct sockaddr_in {
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/string.h
>  #endif // __STRING_H__
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/sys/socket.h
> +#ifndef SOCK_STREAM
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/sys/socket.h
> +#include <stddef.h>
Why include this file hear?

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +#define MAXADDR 12
Remove the useless define

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/src/netdb.c
> +    struct sockaddr *addrs = (struct sockaddr *)malloc(MAXADDR * sizeof(struct sockaddr));
Static allocation is used in musl: `struct address addrs[MAXADDRS];`

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/src/socket.c
Remove the `__` prefixes for all arguments.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/src/socket.c
> +int connect(int __fd, const struct sockaddr *__addr, socklen_t __len)
Add a new line before.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/src/string.c
> +
Remove the blank line.

2023-05-13 07:31 UTC, equation314 commented on ulib/c_libax/src/string.c
> +size_t strspn(const char *s, const char *c)
Move this function after `strcspn()`

2023-05-13 07:31 UTC, equation314 commented on ulib/libax/build.rs
> +            .raw_line("#![allow(non_upper_case_globals)]");
Move this attribute to cbindings/mod.rs:

```rust
#[rustfmt::skip]
#[path = "./ctypes_gen.rs"]
#[allow(dead_code, non_camel_case_types, clippy::upper_case_acronyms)] // add here
mod ctypes;
```

2023-05-13 07:31 UTC, equation314 commented on ulib/libax/ctypes.h
> +#include <sys/types.h> /* See NOTES */
Where is `NOTES`?

2023-05-13 07:31 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
Remove `__` prefixed for all arguments.

2023-05-13 07:47 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
> +fn get_ephemeral_port() -> AxResult<u16> {
tcp 和 udp端口是独立的，如果使用一个的话好像就不能tcp和udp共用端口了

2023-05-13 08:06 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
可以筛选出来自connect对象的回复

2023-05-13 08:09 UTC, reflyable commented on ulib/c_libax/include/netinet/in.h
> +uint32_t htonl(uint32_t);
musl 里这两个文件都定义了

2023-05-13 08:13 UTC, reflyable commented on ulib/c_libax/include/netdb.h
> +#define MAXADDR 12
MAXADDR是配置getaddrinfo最多返回多少个地址，是要在c文件里写吗？

2023-05-13 08:17 UTC, reflyable commented on ulib/c_libax/src/netdb.c
> +    struct sockaddr *addrs = (struct sockaddr *)malloc(MAXADDR * sizeof(struct sockaddr));
是也要按照musl里用calloc aibuf来储存addr吗？

2023-05-13 09:08 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +fn get_ephemeral_port() -> AxResult<u16> {
Use a same function with different states.

2023-05-13 12:10 UTC, equation314 commented on ulib/c_libax/include/netinet/in.h
> +uint32_t htonl(uint32_t);
根据 https://linux.die.net/man/3/htonl，应该声明在 arpa/inet.h，两处都声明也可以。

2023-05-13 12:11 UTC, equation314 commented on ulib/c_libax/src/netdb.c
> +    struct sockaddr *addrs = (struct sockaddr *)malloc(MAXADDR * sizeof(struct sockaddr));
musl 不是直接用一个局部数组来存吗？

2023-05-13 12:16 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
正常应该都会成立 ？如果考虑异常情况也不应该返回 Again

2023-05-13 12:20 UTC, reflyable commented on ulib/c_libax/src/netdb.c
> +    struct sockaddr *addrs = (struct sockaddr *)malloc(MAXADDR * sizeof(struct sockaddr));
musl最后返回的时候相当于把addrs复制到结果的链表里了，我这里则是在结果里直接使用了addrs，没有进行复制。写成直接分配会在getaddrinfo返回后释放addrs，结果会出错

2023-05-13 12:22 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
如果在监听时收到了来自其他地址的包应该丢弃然后继续监听，直到收到来自connect对象的包，所以我理解应该用Again？

2023-05-13 12:25 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
在 connect 后，还会收到其他地址的包吗？

2023-05-13 12:27 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
会的，因为smoltcp本身没有提供udp的connect，我这里connect的部分相当于使用recv_from和send_to自行模拟的

2023-05-13 12:34 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                            if x.1 == peeraddr {
OK, add more comments to explain this reason.

2023-05-13 12:34 UTC, equation314 commented on ulib/c_libax/src/netdb.c
> +    struct sockaddr *addrs = (struct sockaddr *)malloc(MAXADDR * sizeof(struct sockaddr));
Ok, no problem.

2023-05-13 14:02 UTC, equation314 approved these changes

2023-05-13 14:02 UTC, equation314 commented on a.out
Remove this file.

2023-05-13 14:02 UTC, equation314 commented on ulib/c_libax/src/network.c
> +#include <netinet/in.h>
Move the `#include` at the top of the file.

2023-05-13 14:02 UTC, equation314 commented on ulib/c_libax/src/network.c
> +#include <arpa/inet.h>
Move the `#include` at the top of the file.

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +#![allow(unreachable_patterns)]
Arrange `use`s

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +    fn lseek(&self, offset: ctypes::off_t, whence: c_int) -> LinuxResult<ctypes::off_t> {
Rename to `seek`

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +    fn fstat(&self, buf: *mut ctypes::stat) -> LinuxResult<ctypes::ssize_t> {
rename to `stat`, remove the arg `buf`, and return `ctypes::stat`

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +const FILE_LIMIT: usize = 256;
Increase fd limit to 1024.

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +fn get_file_by_fd(fd: c_int) -> LinuxResult<Filelike> {
Let this function be a method of `Filelike`:

```rust
impl FileLike {
    fn from_fd(fd: c_int) -> LinuxResult<Self> {
        // ...
    }
}
```

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +use axnet::{resolve_socket_addr, Ipv4Addr, SocketAddr, TcpSocket, UdpSocket};
Can it be changed to `use crate::net::xxxx` ?

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +pub unsafe extern "C" fn ax_socket(_domain: c_int, _type: c_int, _protocol: c_int) -> c_int {
remove `_` prefixes for all arguments.

Same below.

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn get_socket_by_fd(fd: c_int) -> LinuxResult<Arc<Mutex<Socket>>> {
Let this function be a method of Filelike:

```rust
impl FileLike {
    #[cfg(feature = "net")]    
    fn into_socket(self) -> LinuxResult<Arc<Mutex<Socket>>> {
        // ...
    }
}
```

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        let mut res_socket_addr = *(_socket_addr as *mut ctypes::sockaddr_in);
Check null pointer.

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _addr: *mut ctypes::sockaddr,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        *_socket_len = 16;
Check null pointer, use `core::mem::size_of::<XXX>()` instead of hardcode.

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _buf: *mut c_void,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _buf: *mut c_void,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _socket_addr: *mut ctypes::sockaddr,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                *_socket_len = 16;
Use `size_of`

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _buf: *const c_void,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _buf: *const c_void,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _socket_addr: *const ctypes::sockaddr,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _socket_addr: *const ctypes::sockaddr,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _socket_addr: *const ctypes::sockaddr,
Check null pointer

2023-05-13 14:02 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +            Socket::Udp(udpsocket) => udpsocket.send(buf).map_err(|e| match e {
`From<AxError>` has implemented for `LinuxError`, just use the `?` operator. Same below.

2023-05-13 14:02 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/mod.rs
> +pub(crate) fn get_ephemeral_port(flag: u8) -> AxResult<u16> {
Add a struct `PortAllocator` and its method `get_ephemeral_port`, creates two instances `UDP_PORT_ALLOCATOR` and `TCP_PORT_ALLOCATOR`.

2023-05-13 14:02 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +#define MAXADDR 12
musl uses `MAXADDRS 48`

2023-05-13 14:03 UTC, equation314 requested changes

2023-05-13 14:03 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _socket_fd: c_int,
remove _ prefixes for all arguments. Same below.

2023-05-13 14:30 UTC, reflyable commented on ulib/libax/src/cbindings/socket.rs
> +use axnet::{resolve_socket_addr, Ipv4Addr, SocketAddr, TcpSocket, UdpSocket};
好像不太能，ulib的net没有暴露tcpsocket， udpsocket的功能也不完全一致

2023-05-13 14:43 UTC, reflyable commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn get_socket_by_fd(fd: c_int) -> LinuxResult<Arc<Mutex<Socket>>> {
这样好像会使得socket.rs可见并不需要的Filetype，不太明白好处在哪

2023-05-13 14:58 UTC, reflyable commented on ulib/libax/src/cbindings/socket.rs
> +            Socket::Udp(udpsocket) => udpsocket.send(buf).map_err(|e| match e {
socket里的axerror和linuxerror对应有点复杂，和From<AxError>不完全相符

2023-05-13 15:23 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +            Socket::Udp(udpsocket) => udpsocket.send(buf).map_err(|e| match e {
添加一个 AddrInUse，其他大致相符就可以，参考 https://doc.rust-lang.org/src/std/sys/unix/mod.rs.html

2023-05-13 15:25 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn get_socket_by_fd(fd: c_int) -> LinuxResult<Arc<Mutex<Socket>>> {
当不开启 fs feature 时不会用到。这是 rust 的常用风格。

2023-05-13 15:57 UTC, reflyable commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn get_socket_by_fd(fd: c_int) -> LinuxResult<Arc<Mutex<Socket>>> {
没太明白什么意思，不开启 fs feature 这两个函数好像都不受影响？

2023-05-13 16:03 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn get_socket_by_fd(fd: c_int) -> LinuxResult<Arc<Mutex<Socket>>> {
通过 `FileLike::from_fd(fd).into_socket()` 完成该功能，而不是直接调用一个函数。

2023-05-14 04:23 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +fn get_ephemeral_port() -> AxResult<u16> {
Add TODO comment for feature improvement.

2023-05-14 06:50 UTC, equation314 requested changes

2023-05-14 06:50 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +#define MAXADDR 12
musl uses MAXADDRS 48

2023-05-14 06:50 UTC, equation314 commented on ulib/c_libax/include/unistd.h
>  off_t lseek(int fd, off_t offset, int whence);
lseek, fchown, fsync should be available when `fs` feature is enabled.

2023-05-14 06:50 UTC, equation314 commented on ulib/c_libax/src/unistd.c
> -#ifdef AX_CONFIG_FS
lseek, fchown, fsync, ftruncate  should be available when fs feature is enabled.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) enum Filelike {
pub

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +    pub(super) fn from_fd(fd: c_int) -> LinuxResult<Self> {
All methods can be pub

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn add_new_file(file: File) -> Option<usize> {
pub

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +pub(super) fn add_new_socket(socket: Socket) -> Option<usize> {
pub

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +        *buf = Filelike::from_fd(fd)?.stat()?;
Explicit `unsafe`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        let mid = *(socket_addr as *const ctypes::sockaddr_in);
Explicit `unsafe`

2023-05-14 06:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +    ax_err!(AddrInUse, "no avaliable ports!")
Why return AddrInUse if no available ports?

2023-05-14 06:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +        };
Remove the `;`

2023-05-14 06:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> -
Add this blank line back

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    _socket_len: ctypes::socklen_t,
Rename to `addrlen` (same to the specification), and check if it  equals to `size_of(sockaddr)`.
Same below.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/mod.rs
`pub use self::net::{xxxx};`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +#![allow(unused_variables)]
Try to avoid this attribute.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +    pub(super) fn into_socket(self) -> LinuxResult<Arc<Mutex<Socket>>> {
`#[allow(irrefutable_let_patterns)]`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +                let st = stat_file(&f.lock())?;
Can be written in one line.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +            Filelike::SocketType(s) => {
Can be written in one line.

2023-05-14 06:50 UTC, equation314 commented on crates/axerrno/src/lib.rs
> +    /// The address is used
More detail comments from rust std: `A socket address could not be bound because the address is already in use elsewhere.`

2023-05-14 06:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +    ax_err!(AddrInUse, "no avaliable ports!")
listen_table.rs:63 should return `AddrInUse`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                add_new_socket(Socket::Tcp(TcpSocket::new())).ok_or(LinuxError::ENOMEM)
`ENFILE`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                add_new_socket(Socket::Udp(UdpSocket::new())).ok_or(LinuxError::ENOMEM)
`ENFILE `

2023-05-14 06:50 UTC, equation314 commented on crates/axerrno/src/errno.h
Make this file as close to c_libax/include/errno.h as possible.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +use crate::cbindings::ctypes::{in_addr, sockaddr, sockaddr_in, AF_INET};
Remove these `use`s, and use `ctypes::in_addr`, etc directly.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +pub unsafe extern "C" fn ax_socket(domain: c_int, socktype: c_int, protocol: c_int) -> c_int {
Print debug info about arguments for all `ax_*` functions, refers to file.rs. Same below.

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        debug!("Binding {:?}:{}", address, ports);
Unified with the debug information format in file.rs

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        debug!("Connecting {:?}:{}", address, ports);
Unified format

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    let addr_slice = slice_from_raw_parts_mut(addr as *mut sockaddr_in, len);
Why use `slice_from_raw_parts_mut` instead of `core::slice::from_raw_parts_mut`?

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        let name = CStr::from_ptr(node)
use `char_ptr_to_str`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                (*res_socket_addr).sin_family = ctypes::AF_INET as u16;
Create a function to fill `socketaddr`

2023-05-14 06:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        let mid = *(socket_addr as *const ctypes::sockaddr_in);
Create a function to convert `sockaddr` to `(Ipv4Addr, u16)`

2023-05-14 09:38 UTC, reflyable commented on ulib/c_libax/include/unistd.h
>  off_t lseek(int fd, off_t offset, int whence);
这几个函数都是接受fd作为参数，理论上也可以对socket使用，fchown, fsync不支持socket的话应该返回-1, lseek支持socket

2023-05-14 11:35 UTC, equation314 commented on ulib/c_libax/include/unistd.h
>  off_t lseek(int fd, off_t offset, int whence);
这些函数给 socket 用也是没意义的，不如直接不提供。Linux 无法区分是 file 还是 socket，但我们可以。

2023-05-14 11:36 UTC, equation314 commented on ulib/c_libax/include/unistd.h
>  off_t lseek(int fd, off_t offset, int whence);
根据 https://linux.die.net/man/2/lseek，lseek 无法对 socket 操作，永远返回 ESPIPE，所以也是可以不提供给 net 的。

2023-05-14 14:40 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +            Err(LinuxError::ENOTSOCK)
ESPIPE

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/file.rs
>  use super::fd_table::add_new_file;
`use super::fd_table::{FileLike, add_new_file};`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/file.rs
> +use crate::cbindings::fd_table;
Remove this

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +use crate::cbindings::utils::char_ptr_to_str;
`use super::utils::char_ptr_to_str;`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/fd_table.rs
> +            Err(LinuxError::ENOTSOCK)
`ESPIPE`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +fn fill_sockaddr(addr: &SocketAddr) -> ctypes::sockaddr {
`unsafe fn as_c_sockaddr`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +fn load_sockaddr(addr: *const ctypes::sockaddr) -> LinuxResult<SocketAddr> {
`unsafe fn from_c_sockaddr(addr: *const ctypes::sockaddr, addrlen: socklen_t)`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        *(&ctypes::sockaddr_in {
dereference is unnecessary:

```rust
ctypes::sockaddr_in {
    // ...
}
```

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    let mid = unsafe { *(addr as *const ctypes::sockaddr_in) };
Check `addr` and `addrlen` validation here, and no need to check in other place.

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        socket_fd, socket_addr as usize, addrlen
Print a meaningful `socket_addr` (after `load_sockaddr`), rather than print a raw pointer.

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        socket_fd, buf_ptr as usize, len, _flag, socket_addr as usize, addrlen
Print a meaningful `socket_addr`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        socket_fd, socket_addr as usize, addrlen
Print a meaningful `socket_addr`

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
>      _backlog: c_int, // no effect
can be change to `backlog`. Same as `_flag` in the above functions.

2023-05-14 16:34 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    let addr_slice = unsafe { core::slice::from_raw_parts_mut(addr, len) };
Convert to slice after null pointer check.

2023-05-14 16:34 UTC, equation314 commented on ulib/c_libax/src/unistd.c
> +}
add a blank line after

2023-05-14 16:34 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +#define MAXADDR 48
`MAXADDRS`

2023-05-14 16:54 UTC, reflyable commented on ulib/libax/src/cbindings/socket.rs
> +        *(&ctypes::sockaddr_in {
sockaddr_in 不通过指针好像不能转成sockaddr

2023-05-14 17:09 UTC, equation314 commented on ulib/libax/src/cbindings/file.rs
> +pub unsafe extern "C" fn ax_lseek(
Move this function after `ax_open`

2023-05-14 17:12 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    debug!("Load sockaddr:{:#x} => {:?}", addr as usize, res);
Add indent: `debug!("  load sockaddr ...")`

2023-05-14 17:37 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +use super::fd_table;
use `super::fd_table::{self, FileLike};`

2023-05-14 17:39 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +    node: *const c_char,
`node` is not actually use?

2023-05-14 18:17 UTC, closed without merging