Iperf
arceos-org/arceos pull request #58
Opened 2023-05-27 15:10 UTC by reflyable

将Iperf3迁移到Arceos，可以通过iperf_api正常使用
基本未更改iperf3源代码，只是注释/用0替换了部分获取硬件信息的函数，将头文件引用修改为clibax，替换了不必要的复杂函数
经测试可以进行server和client的连接，作为server进行udp连接时需要在client指定-l=1300(性能较佳), 大于14xx会导致smoltcp丢弃而收不到udp包。
主要更改:
- 引入[嵌入式printf实现](https://github.com/mpaland/printf)来支持更完全的vsnprintf及snprintf
- 支持若干基本的浮点数库函数
- 实现select库函数

2023-05-28 08:28 UTC, equation314 commented on log.txt
Remove these two files

2023-05-28 14:16 UTC, equation314 commented on modules/axfs/resources/fat16.img
Restore this file.

2023-06-01 13:15 UTC, equation314 requested changes

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/src/unistd.c
> +    errno = a < 0 ? -a : 0;
Restore changes

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/include/fcntl.h
> +#define S_ISUID 04000
Wrap in `#ifndef S_IRUSR`

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +static unsigned int h_errno;
Change to `extern int h_errno;`, and add `int h_errno;` in "network.c".

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/include/netdb.h
> +static unsigned int h_errno;
Add more definitions about `h_errno`:

```c
#define HOST_NOT_FOUND 1
#define TRY_AGAIN      2
#define NO_RECOVERY    3
#define NO_DATA        4
#define NO_ADDRESS     NO_DATA
```

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/src/network.c
> +    return "";
Copy from musl?

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/include/math.h
> +static inline void fp_force_evalf(float x)
Move these two functions into `math.c`

2023-06-01 13:15 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +    pub fn set_nonblock(&mut self, nonblock: bool) {
```rust
pub fn set_nonblocking(&mut self, nonblocking: bool) {}
```

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/fd_ops.rs
> +    fn is_ready(&self) -> LinuxResult<[bool; 3]>;
```rust
fn poll(&self) -> LinuxResult<PollState>;

// in crates/axio
pub struct PollState {
    pub readable: bool,
    pub writable: bool,
}
```

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/fd_ops.rs
> +    fn set_status_flags(&self, arg: usize) -> LinuxResult;
```rust
fn set_nonblocking(&self, nonblocking: bool);
```

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/fd_ops.rs
> +pub unsafe extern "C" fn ax_select(
Move into `cbindings/io/select.rs`

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                .unwrap_or_else(|_| (Ipv4Addr::from_bytes(&(0_u32).to_be_bytes()), 0).into())),
`unwrap_or_default()`

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/fd_ops.rs
> +                get_file_like(fd)?.set_status_flags(arg)?;
only support `O_NONBLOCK`

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/mod.rs
> +    ax_sendto, ax_setsockopt, ax_shutdown, ax_socket,
`ax_getsockname` and more?

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/src/select.c
> +    unimplemented();
Call `ax_select` and ignore `mask`.

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/src/select.c
> +        errno = EINVAL;
`return -EINVAL`

2023-06-01 13:15 UTC, equation314 commented on ulib/c_libax/src/select.c
> +#define CLAMP(x)   (int)(IS32BIT(x) ? (x) : 0x7fffffffU + ((0ULL + (x)) >> 63))
not used?

2023-06-01 13:15 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +    pub fn is_ready(&self) -> AxResult<[bool; 3]> {
```rust
pub fn poll(&self) -> AxResult<PollState>;
```

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/fd_ops.rs
> +    for i in 0..1024 {
`0..nfds`

2023-06-01 13:15 UTC, equation314 commented on ulib/libax/src/cbindings/fd_ops.rs
> +    n: c_int,
More detail variable names: `nfds`, `readfds`, `writefds`, `expectfds`, `timeout`.

2023-06-02 08:48 UTC, equation314 commented on ulib/c_libax/src/select.c
> +        return -EINVAL;
Since `errno` is working on the latest main branch, it should return `-1`.

2023-06-02 08:56 UTC, equation314 commented on ulib/libax/src/cbindings/pipe.rs
> +            readable: self.readable(),
Also check `buffer.available_read() > 0` and `buffer.available_write() > 0`.

2023-06-02 09:07 UTC, equation314 commented on ulib/libax/src/cbindings/pipe.rs
> +    fn poll(&self) -> LinuxResult<PollState> {
Call `buffer.lock()` only once

2023-06-02 09:12 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                    port.map(|p| p.parse::<u16>().unwrap_or(0)).unwrap_or(0),
`port.and_then(|p| p.parse<u16>()).unwrap_or(0)`

2023-06-02 09:13 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                    .into(),
`SocketAddr::from(...)` is more clearly.

2023-06-02 09:18 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +/// Query addresses for a domain name.
Wrong comments

2023-06-02 09:18 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +        match level as u32 {
Merge into one `match`

2023-06-02 09:21 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +            ctypes::SOL_SOCKET => match optname as u32 {
Since there is no meaningful operation yet, this `ax_*` function can be removed and written in `c_libax/network.c` instead.

2023-06-02 09:26 UTC, equation314 commented on ulib/c_libax/include/math.h
> +{
Add comments about `fp_force_eval` from musl.

2023-06-02 09:29 UTC, equation314 commented on apps/c/iperf/diff.patch
> ++perror(char *message)
Remove it.

2023-06-02 09:31 UTC, equation314 commented on apps/c/iperf/diff.patch
> ++void perror(char *message);
Remove it

2023-06-02 09:34 UTC, equation314 commented on apps/c/iperf/diff.patch
> ++int main() {
Create a new file such as `main_mini.c` to minimize changes.

2023-06-02 09:36 UTC, equation314 commented on apps/c/iperf/diff.patch
> ++  int port;
Use 4-space indent.

2023-06-02 09:41 UTC, equation314 commented on apps/c/iperf/diff.patch
Rename to `iperf.patch`

2023-06-02 09:42 UTC, reflyable commented on ulib/libax/src/cbindings/socket.rs
> +                    port.map(|p| p.parse::<u16>().unwrap_or(0)).unwrap_or(0),
Error mismatch

2023-06-02 09:48 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                    port.map(|p| p.parse::<u16>().unwrap_or(0)).unwrap_or(0),
`port.map_or(0, |p| p.parse<u16>().unwrap_or(0))`

2023-06-02 09:52 UTC, equation314 commented on apps/c/iperf/Readme.md
`README.md`

2023-06-02 09:53 UTC, equation314 commented on apps/c/iperf/diff.patch
> ++  exit(0);
`return 0;`

2023-06-02 10:03 UTC, equation314 commented on ulib/c_libax/include/netinet/tcp.h
> +
Add `struct tcp_info`, so that we can remove the `-Ulinux` flag when build iperf.

2023-06-02 10:08 UTC, reflyable commented on ulib/c_libax/include/netinet/tcp.h
> +
tcpinfo相关功能需要getsockopt实现，smoltcp不太好支持

2023-06-02 10:10 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +    /// Mark the socket nonblock, for POSIX.
More detail comments from rust_std: https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_nonblocking

2023-06-02 10:15 UTC, equation314 commented on ulib/c_libax/include/netinet/tcp.h
> +
删掉这些 `#define`, 使得 iperf 中的 `defined(TCP_INFO)` 判断不通过？

2023-06-02 10:25 UTC, reflyable commented on ulib/c_libax/include/netinet/tcp.h
> +
在别的文件中会用到这些define(虽然实际上并没用到，但会编译不过）

2023-06-02 10:32 UTC, equation314 commented on ulib/c_libax/include/netinet/tcp.h
> +
OK

2023-06-02 11:50 UTC, equation314 commented on ulib/c_libax/src/socket.c
> +    return 0;
add `unimplemented();`

2023-06-02 11:50 UTC, equation314 commented on ulib/libax/src/cbindings/errno.rs
> +    debug!("h1");
Remove debug info

2023-06-02 11:50 UTC, equation314 commented on modules/axhal/linker.lds.S
> +}
new line at EOF

2023-06-02 11:50 UTC, equation314 commented on ulib/c_libax/include/math.h
> +static inline void fp_force_evalf(float x)
These two functions should not be placed in `math.h` and export to users.

2023-06-02 11:50 UTC, equation314 commented on ulib/c_libax/src/socket.c
> +    printf("debug out: func = %-25s,line = %4d, file = %s\r\n", __FUNCTION__, __LINE__, __FILE__);
Remove debug info

2023-06-02 15:43 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +            .ok_or_else(|| ax_err_type!(InvalidInput, "socket accept() failed: no address bound"))?
Wrong message.

2023-06-02 15:43 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +            .ok_or_else(|| ax_err_type!(InvalidInput, "socket is_ready() failed"))?;
Wrong message

2023-06-02 15:43 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +                readable: socket.is_open() && socket.may_send() && socket.can_recv(),
`may_recv()`/`may_send()` is no need to check.

2023-06-02 15:43 UTC, equation314 commented on crates/axio/src/lib.rs
> +pub struct PollState {
`#[derive(Debug)]`

2023-06-03 03:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +    pub fn ready(&self, port: u16) -> AxResult<bool> {
`can_accept`

2023-06-03 03:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +                writable: ready,
`writable` is always
false for a listener？

2023-06-03 03:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
>      handle: Option<SocketHandle>,
`Option` is unnecessary.

2023-06-03 03:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +        fn get_socket_info(handle: SocketHandle) -> (bool, Option<SocketAddr>) {
Move this common function out of `struct ListenTable`.

2023-06-03 03:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +            if let Some(&handle) = syn_queue.front() {
Check if connected in one loop:
```rust
if syn_queue
      .iter()
      .find(|(&handle| {
         let (connected, _) = get_socket_info(handle);
         connected
}) {
    Ok(true)
} else {
    Ok(false)
}
```

2023-06-03 03:50 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
Implement `recv` by `recv_from`?

2023-06-03 03:50 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                .unwrap_or_else(|_| (Ipv4Addr::from_bytes(&(0_u32).to_be_bytes()), 0).into())),
`unwrap_or_default`

2023-06-03 03:50 UTC, equation314 commented on apps/c/iperf/iperf.patch
> +-
Unnecessary change

2023-06-03 03:50 UTC, equation314 commented on apps/c/iperf/Readme.md
Uppercase file name: README.md

2023-06-03 03:50 UTC, equation314 commented on apps/c/iperf/Readme.md
> +iperf3 -uc 0.0.0.0 -p 5555 -l 1300 -b <Approximate Bandwidth (30MB as an example)>
Add tcp/udp server/client commands.

2023-06-03 03:50 UTC, equation314 commented on apps/c/iperf/iperf.patch
> +-int
It's better to comment the code block around `/* */`?

2023-06-03 06:54 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
因为recv要做筛选，如果用recv_from实现就要多套一层循环，多传一层异常，感觉不如直接改

2023-06-03 06:56 UTC, reflyable commented on ulib/libax/src/cbindings/socket.rs
> +                .unwrap_or_else(|_| (Ipv4Addr::from_bytes(&(0_u32).to_be_bytes()), 0).into())),
SocketAddr没有defalut

2023-06-03 07:11 UTC, reflyable commented on apps/c/iperf/iperf.patch
> +-int
这样的话diff文件会变大很多，而且感觉没什么意义？

2023-06-03 07:24 UTC, equation314 commented on apps/c/iperf/iperf.patch
> +-int
`/* */` only adds two lines in the `diff` file.

2023-06-03 07:26 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                .unwrap_or_else(|_| (Ipv4Addr::from_bytes(&(0_u32).to_be_bytes()), 0).into())),
`Ipv4Addr` has `default()`

2023-06-03 07:46 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
Remove `&` before `handle`

2023-06-03 07:46 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +        SOCKET_SET.with_socket_mut::<udp::Socket, _, _>(self.handle, |socket| {
Put `SOCKET_SET.poll_interfaces()` at the end of the function.

2023-06-03 07:46 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/tcp.rs
> +    pub fn poll(&self) -> AxResult<PollState> {
```rust
if let Some(handle) = self.handle {
    // steam
    Ok(PollState {...})
} else {
   // listener
   Ok(PollState {...})
}
```

2023-06-03 07:46 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +            if syn_queue
```rust
if entry.syn_queue.iter()...
```

2023-06-03 07:46 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +                .find(|&handle| {
Sorry, use `iter().any()` is better.

2023-06-03 07:46 UTC, equation314 commented on ulib/c_libax/src/math.c
> +static const double toint = 1 / 2.2204460492503131e-16;
`DBL_EPSILON`?

2023-06-03 07:46 UTC, equation314 commented on ulib/libax/src/cbindings/socket.rs
> +                port.map(|p| p.parse::<u16>().unwrap_or(0)).unwrap_or(0),
`port.map_or(0, |p| p.parse<u16>().unwrap_or(0))`?

2023-06-03 07:52 UTC, reflyable commented on apps/c/iperf/iperf.patch
> +-int
因为它函数内部有很多*/所以不能只在头尾加

2023-06-03 07:54 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
这样的话can_accept里面就要解引用？

2023-06-03 07:55 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
Keep the `&` before `SocketHandle`.

2023-06-03 07:56 UTC, equation314 commented on apps/c/iperf/iperf.patch
> +-int
```c
#if 0
#endif
```

2023-06-03 07:57 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
那里面with_socket就要解引用？

2023-06-03 07:59 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
Remove all `&` ?

2023-06-03 08:01 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
主要是can_accept里面是&SocketHandle的类型，别的地方都是SocketHandle的类型，总有地方对不上

2023-06-03 08:07 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/listen_table.rs
> +fn get_socket_info(&handle: &SocketHandle) -> (bool, Option<SocketAddr>) {
闭包里已经有 `&handle` 了，表示 `handle` 是实际类型而不是引用：

```rust
if entry.syn_queue.iter().any(|&handle| {
    let (connected, _peer_addr) = get_socket_info(handle);
    connected
}) {
    Ok(true)
} else {
    Ok(false)
}
```

2023-06-03 09:14 UTC, equation314 commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                Err(_) => Err(AxError::WouldBlock),
Why return `WouldBlock` on other errors?

2023-06-03 09:17 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                Err(_) => Err(AxError::WouldBlock),
实际上只会在缓冲区满的时候返回RecvError::Exhausted

2023-06-03 09:18 UTC, reflyable commented on modules/axnet/src/smoltcp_impl/udp.rs
> +                Err(_) => Err(AxError::WouldBlock),
没有别的错误类型

2023-06-03 09:42 UTC, equation314 approved these changes

2023-06-05 07:20 UTC, merged