add support of PLATFORM=raspi4-aarch64
arceos-org/arceos pull request #71
Opened 2023-06-05 05:39 UTC by MrRobertYuan

add support of PLATFORM=raspi4-aarch64
You can run the apps which are independent of virtio-device on Raspberry 4B with features "ARCH=aarch64 PLATFORM=raspi4-aarch64".
The specific command about how to run and debug on raspi4 are written in /docs/raspi4.md

2023-06-05 22:22 UTC, chyyuu commented
Good work!

2023-06-06 12:31 UTC, equation314 requested changes

2023-06-06 12:31 UTC, equation314 commented on modules/axconfig/src/platform/raspi4-aarch64.toml
> +phys-memory-size = "0x800_0000"     # 128M
4G ?

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/arch/aarch64/mod.rs
> +/// Flushes the data cache at addr
`Flushes the data cache line (64 bytes) at the given virtual address`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/arch/aarch64/mod.rs
> +pub fn flush_dcache_line(addr: usize) {
`vaddr: VirtAddr`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/build.rs
> +    #[cfg(not(feature = "platform-raspi4-aarch64"))]
Create different linker scripts for different platform, e.g., `linker_qemu-virt-aarch64.lds`, `linker_raspi4-aarch64.lds`.

2023-06-06 12:31 UTC, equation314 commented on Makefile
> +	LD_SCRIPT := $(CURDIR)/modules/axhal/linker_$(ARCH)_raspi4.lds
`LD_SCRIPT := $(CURDIR)/modules/axhal/linker_$(PLATFORM).lds`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/mod.rs
> +        pub use self::aarch64_common::*;
Do not `pub use self::aarch64_common::*`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/aarch64_common/mod.rs
> +#[cfg(feature = "irq")]
Do not define high-level `mod`s here, move these into `qemu_virt_aarch64/mod.rs` and `raspi4_aarch64/mod.rs`.

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/aarch64_common/generic_timer.rs
> +pub fn init_early() {
`pub(crate)`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/aarch64_common/generic_timer.rs
> +pub fn init_percpu() {
`pub(crate)`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/aarch64_common/gic.rs
> +pub fn init_primary() {
`pub(crate)`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/aarch64_common/pl011.rs
> +    #[cfg(feature = "irq")]
Split into two functions: `init_early()` and `init()`, and enable IRQs after GIC initialization.

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mem.rs
> +        Ordering::Greater => extern_memory_region_at(idx),
`idx - common_memory_regions_num()`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/boot.rs
`boot.rs` is almost the same as in `qemu_virt_aarch64`, merge into one.

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +    let entry_address = virt_to_phys(VirtAddr::from(modify_stack_and_start as usize)).as_usize();
`entry_paddr`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +            virt_to_phys(VirtAddr::from(
`flush_dcache_line` use virtual address?

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +#[no_mangle]
No need to use `#[no_mangle]`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +#[no_mangle]
No need to use `#[no_mangle]`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +    asm::sev();
use full path: `aarch64_cpu::asm::sev()`

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +#[no_mangle]
Add `#[naked]`, `
#[link_section = ".text.boot"]`. `#[no_mangle]` is no need.

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +        sub     x21, x21, x8
`SECONDARY_STACK_TOP` is already use the physical address?

2023-06-06 12:31 UTC, equation314 commented on modules/axhal/src/platform/raspi4_aarch64/mp.rs
> +        b       {start_secondary}",
`b    _start_secondary` is ok.

2023-06-06 12:42 UTC, equation314 commented on crates/arm_pl011/src/pl011.rs
> +        self.regs().icr.set(0x3ff);
`0x7ff`

2023-06-06 12:49 UTC, equation314 commented on crates/arm_pl011/src/pl011.rs
> +    pub fn handle(&mut self) {
Split into two functions: 

1. `ack_interrupts()`: set ICR.
2. `is_receive_interrupt()`: return `pending & (1 << 4) != 0`.

2023-06-07 13:59 UTC, closed without merging